server:
  port: 9999
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/gmb_postgres
    username: gmb_user
    password: gmb
    driverClassName: org.postgresql.Driver
